MOLECULES = [
    {"name": "Artesunate", "cas": "88495-63-0", "grades": ["IP", "USP", "BP"], "category": "Antimalarial"},
    {"name": "Asenapine", "cas": "65576-45-6", "grades": ["IP", "BP", "USP", "JP"], "category": "Antipsychotic"},
    {"name": "Aspirin", "cas": "50-78-2", "grades": ["USP", "BP", "EP"], "category": "NSAID"},
    {"name": "Axitinib", "cas": "319469-85-0", "grades": ["USP", "BP", "JP"], "category": "Anticancer"},
    {"name": "Azaperone", "cas": "111-49-9", "grades": ["USP", "EP", "BP"], "category": "Antipsychotic"},
    {"name": "Azelastine", "cas": "58581-89-8", "grades": ["USP"], "category": "Antihistamine"},
    {"name": "Azilsartan", "cas": "147404-03-0", "grades": ["USP", "EP", "IP", "BP"], "category": "Antihypertensive"},
    {"name": "Aztreonam", "cas": "78110-38-0", "grades": ["USP", "EP", "BP"], "category": "Antibiotic"},
    {"name": "Baclofen", "cas": "1134-47-0", "grades": ["USP", "BP", "EP"], "category": "Muscle Relaxant"},
    {"name": "Balofloxacin", "cas": "127294-70-6", "grades": ["USP", "EP"], "category": "Antibiotic"},
    {"name": "Brivaracetam", "cas": "357336-20-0", "grades": ["EP"], "category": "Antiepileptic"},
    {"name": "Bromfenac", "cas": "91714-94-2", "grades": ["JP"], "category": "NSAID"},
    {"name": "Busulfan", "cas": "55-98-1", "grades": ["BP", "EP", "USP"], "category": "Anticancer"},
    {"name": "Canagliflozin", "cas": "842133-18-0", "grades": ["IP", "EP", "USP"], "category": "Antidiabetic"},
    {"name": "Candesartan", "cas": "139481-59-7", "grades": ["USP", "EP", "BP"], "category": "Antihypertensive"},
    {"name": "Carmoterol", "cas": "147568-66-9", "grades": ["USP", "EP", "BP", "JP"], "category": "Bronchodilator"},
    {"name": "Carprofen", "cas": "53716-49-7", "grades": ["EP", "USP"], "category": "NSAID"},
    {"name": "Cefadroxil", "cas": "66592-87-8", "grades": ["USP", "EP", "BP"], "category": "Antibiotic"},
    {"name": "Cefepime", "cas": "123171-59-5", "grades": ["USP", "EP", "BP"], "category": "Antibiotic"},
    {"name": "Cefixime", "cas": "79350-37-1", "grades": ["USP", "EP", "BP", "IP"], "category": "Antibiotic"},
    {"name": "Cefradine", "cas": "38821-53-3", "grades": ["USP", "EP", "BP"], "category": "Antibiotic"},
    {"name": "Cetrorelix", "cas": "120287-85-6", "grades": ["USP", "EP", "BP", "IP"], "category": "Hormone"},
    {"name": "Ciprofloxacin", "cas": "85721-33-1", "grades": ["USP", "EP", "BP"], "category": "Antibiotic"},
    {"name": "Clevidipine", "cas": "167221-71-8", "grades": ["USP", "EP", "BP", "IP"], "category": "Antihypertensive"},
    {"name": "Clonazepam", "cas": "1622-61-3", "grades": ["USP", "EP", "BP", "IP"], "category": "Anxiolytic"},
    {"name": "Dabrafenib", "cas": "1195765-45-7", "grades": ["USP", "EP", "BP"], "category": "Anticancer"},
    {"name": "Dapagliflozin", "cas": "461432-26-8", "grades": ["USP"], "category": "Antidiabetic"},
    {"name": "Dasatinib", "cas": "302962-49-8", "grades": ["USP"], "category": "Anticancer"},
    {"name": "Diazoxide", "cas": "364-98-7", "grades": ["USP", "EP"], "category": "Antihypertensive"},
    {"name": "Diltiazem", "cas": "3386-22-5", "grades": ["USP", "EP", "BP"], "category": "Antihypertensive"},
    {"name": "Diosmin", "cas": "520-27-4", "grades": ["USP", "EP"], "category": "Venotonic"},
    {"name": "Docetaxel", "cas": "114977-28-5", "grades": ["USP", "EP"], "category": "Anticancer"},
    {"name": "Donepezil", "cas": "120014-06-4", "grades": ["USP", "EP", "BP"], "category": "Cholinesterase Inhibitor"},
    {"name": "Dorzolamide", "cas": "130693-82-2", "grades": ["USP", "EP", "BP"], "category": "Antiglaucoma"},
    {"name": "Edoxaban", "cas": "480449-70-5", "grades": ["USP", "EP", "BP"], "category": "Anticoagulant"},
    {"name": "Enalapril Maleate", "cas": "76095-16-4", "grades": ["USP", "EP", "BP"], "category": "Antihypertensive"},
    {"name": "Eptifibatide", "cas": "188627-80-7", "grades": ["USP"], "category": "Antiplatelet"},
    {"name": "Erlotinib", "cas": "183321-74-6", "grades": ["USP", "EP"], "category": "Anticancer"},
    {"name": "Ertugliflozin", "cas": "1210344-57-2", "grades": [], "category": "Antidiabetic"},
    {"name": "Estriol", "cas": "50-27-1", "grades": ["USP", "EP"], "category": "Hormone"},
    {"name": "Felodipine", "cas": "72509-76-3", "grades": ["USP", "EP", "BP"], "category": "Antihypertensive"},
    {"name": "Ferrous Fumarate", "cas": "141-01-5", "grades": ["USP", "EP", "BP", "IP"], "category": "Mineral Supplement"},
    {"name": "Fingolimod", "cas": "162359-55-9", "grades": ["USP", "EP"], "category": "Immunomodulator"},
    {"name": "Firocoxib", "cas": "189954-96-9", "grades": ["USP", "BP"], "category": "NSAID"},
    {"name": "Florfenicol", "cas": "73231-34-2", "grades": ["USP", "BP"], "category": "Antibiotic"},
    {"name": "Romidepsin", "cas": "128517-07-7", "grades": ["USP", "EP", "BP", "IP"], "category": "Anticancer"},
    {"name": "Roxithromycin", "cas": "80214-83-1", "grades": ["EP"], "category": "Antibiotic"},
    {"name": "Rufinamide", "cas": "106308-44-5", "grades": ["USP"], "category": "Antiepileptic"},
    {"name": "Hexetidine", "cas": "141-94-6", "grades": ["EP"], "category": "Antiseptic"},
    {"name": "Ibuprofen", "cas": "15687-27-1", "grades": ["USP", "EP", "BP"], "category": "NSAID"},
    {"name": "Idebenone", "cas": "58186-27-9", "grades": [], "category": "Nootropic"},
    {"name": "Imeglimin", "cas": "775351-65-0", "grades": ["IP"], "category": "Antidiabetic"},
    {"name": "Imiquimod", "cas": "99011-02-6", "grades": ["USP"], "category": "Immunomodulator"},
    {"name": "Iohexol", "cas": "66108-95-0", "grades": ["USP", "EP"], "category": "Contrast Agent"},
    {"name": "Ketotifen Fumarate", "cas": "34580-14-8", "grades": ["USP", "EP"], "category": "Antihistamine"},
    {"name": "Lafutidine", "cas": "118288-08-7", "grades": ["USP", "EP", "BP", "IP"], "category": "H2 Blocker"},
    {"name": "Letrozole", "cas": "112809-51-5", "grades": ["USP", "EP", "BP", "IP"], "category": "Anticancer"},
    {"name": "Levetiracetam", "cas": "102767-28-2", "grades": ["USP", "EP", "BP"], "category": "Antiepileptic"},
    {"name": "Linagliptin", "cas": "668270-12-0", "grades": ["USP", "EP", "BP"], "category": "Antidiabetic"},
    {"name": "Lisinopril", "cas": "83915-83-7", "grades": ["USP", "EP", "BP", "IP"], "category": "Antihypertensive"},
    {"name": "Lacosamide", "cas": "175481-36-4", "grades": ["USP", "EP", "BP", "IP"], "category": "Antiepileptic"},
    {"name": "Lufenuron", "cas": "103055-07-8", "grades": ["USP", "EP"], "category": "Antiparasitic"},
    {"name": "Luliconazole", "cas": "18164-19-8", "grades": ["USP", "EP", "BP", "IP"], "category": "Antifungal"},
    {"name": "Mebendazole", "cas": "31431-39-7", "grades": ["USP", "EP", "BP"], "category": "Antiparasitic"},
    {"name": "Melatonin", "cas": "73-31-4", "grades": ["USP", "EP", "BP"], "category": "Hormone"},
    {"name": "Mepatazinol", "cas": "53340-58-8", "grades": ["BP"], "category": "Analgesic"},
    {"name": "Metolazone", "cas": "17560-51-9", "grades": ["USP", "EP"], "category": "Diuretic"},
    {"name": "Mifepristone", "cas": "84371-65-3", "grades": ["USP"], "category": "Hormone"},
    {"name": "Mirtazapine", "cas": "85650-52-8", "grades": ["USP", "EP", "BP"], "category": "Antidepressant"},
    {"name": "Naloxone", "cas": "465-65-6", "grades": ["USP", "EP", "BP"], "category": "Opioid Antagonist"},
    {"name": "Nelfinavir", "cas": "159989-65-8", "grades": ["USP", "EP"], "category": "Antiviral"},
    {"name": "Neomycin", "cas": "1405-10-3", "grades": ["USP", "EP", "BP"], "category": "Antibiotic"},
    {"name": "Nepafenac", "cas": "78281-72-8", "grades": ["USP", "EP", "BP", "IP"], "category": "NSAID"},
    {"name": "Nicarbazin", "cas": "330-95-0", "grades": ["IP"], "category": "Antiparasitic"},
    {"name": "Nicardipine", "cas": "54527-84-3", "grades": ["USP", "EP"], "category": "Antihypertensive"},
    {"name": "Nifedipine", "cas": "21827-25-4", "grades": ["USP", "EP", "BP"], "category": "Antihypertensive"},
    {"name": "Nimodipine", "cas": "66085-59-4", "grades": ["USP", "EP", "BP"], "category": "Neuroprotective"},
    {"name": "Nisoldipine", "cas": "63675-72-9", "grades": ["USP", "EP"], "category": "Antihypertensive"},
    {"name": "Nizatidine", "cas": "76963-41-2", "grades": ["USP", "EP"], "category": "H2 Blocker"},
    {"name": "Norfloxacin", "cas": "70458-96-7", "grades": ["USP", "EP", "BP"], "category": "Antibiotic"},
    {"name": "Octenidine", "cas": "70775-75-6", "grades": ["USP", "EP", "BP", "IP"], "category": "Antiseptic"},
    {"name": "Ofloxacin", "cas": "82419-36-1", "grades": ["USP", "EP", "BP"], "category": "Antibiotic"},
    {"name": "Olanzapine", "cas": "132539-06-2", "grades": ["USP", "EP", "BP"], "category": "Antipsychotic"},
    {"name": "Ondansetron", "cas": "99614-02-5", "grades": ["USP", "EP", "BP", "IP"], "category": "Antiemetic"},
    {"name": "Oxetacaine", "cas": "126-27-2", "grades": ["USP", "EP", "BP", "IP"], "category": "Analgesic"},
    {"name": "Oxiracetam", "cas": "62613-82-5", "grades": ["USP", "EP"], "category": "Nootropic"},
    {"name": "Safinamide", "cas": "133865-89-1", "grades": ["USP", "BP"], "category": "Antiparkinsonian"},
    {"name": "Saxagliptin", "cas": "361442-04-8", "grades": ["USP", "EP"], "category": "Antidiabetic"},
    {"name": "Parecoxib", "cas": "198470-84-7", "grades": ["USP", "EP", "BP"], "category": "NSAID"},
    {"name": "Pazopanib", "cas": "444731-52-6", "grades": [], "category": "Anticancer"},
    {"name": "Pefloxacin", "cas": "70458-92-3", "grades": ["EP", "IP"], "category": "Antibiotic"},
    {"name": "Peramivir", "cas": "330600-85-6", "grades": ["USP", "EP"], "category": "Antiviral"},
    {"name": "Pidotimod", "cas": "121808-62-6", "grades": ["USP", "EP", "BP"], "category": "Immunomodulator"},
    {"name": "Pimozide", "cas": "2062-78-4", "grades": ["USP", "EP", "BP"], "category": "Antipsychotic"},
    {"name": "Primidone", "cas": "125-33-7", "grades": ["USP", "EP", "BP"], "category": "Antiepileptic"},
    {"name": "Selamectin", "cas": "220119-17-5", "grades": ["USP", "EP"], "category": "Antiparasitic"},
    {"name": "Silodosin", "cas": "160970-54-7", "grades": ["USP", "EP", "BP", "IP"], "category": "Alpha Blocker"},
    {"name": "Simvastatin", "cas": "79902-63-9", "grades": ["USP", "EP", "BP", "IP"], "category": "Statin"},
    {"name": "Sirolimus", "cas": "53123-88-9", "grades": ["USP", "EP"], "category": "Immunosuppressant"},
    {"name": "Sofosbuvir", "cas": "1190307-88-0", "grades": ["USP"], "category": "Antiviral"},
    {"name": "Sorafenib", "cas": "284461-73-0", "grades": ["USP", "EP"], "category": "Anticancer"},
    {"name": "Sotagliflozin", "cas": "1018899-04-1", "grades": ["USP", "EP"], "category": "Antidiabetic"},
    {"name": "Stanozolol", "cas": "10418-03-8", "grades": ["USP", "EP", "BP"], "category": "Anabolic Steroid"},
    {"name": "Sulbactam", "cas": "68373-14-8", "grades": ["USP", "EP"], "category": "Beta-Lactamase Inhibitor"},
    {"name": "Piracetam", "cas": "7491-74-9", "grades": ["USP", "EP"], "category": "Nootropic"},
    {"name": "Pranlukast", "cas": "103177-37-3", "grades": ["EP"], "category": "Antiasthmatic"},
]

CATEGORIES = sorted(set(m["category"] for m in MOLECULES))
